version: '3'
services:
  app:
    build: 
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/myapp
      - POSTGRES_URI=postgresql://postgres:postgresPassword@postgres:5432/myapp
      - NODE_ENV=development
    depends_on:
      - mongo
      - postgres
      - internal-api
    volumes:
      - ./web:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npm run db:migrate && npm install && npm start"

  internal-api:
    build:
      context: ./internal-api
      dockerfile: Dockerfile
    environment:
      - SECRET_KEY=supersecretkey123
    command: sh -c "npm install && npm start"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=myapp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgresPassword
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data 

volumes:
  mongodb_data:
  postgres_data: